[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "modis"
version = "0.1.0"
description = "Multimodal data integration"
authors = [{ name = "Daniel", email = "dlsoltero@gmail.com" }]
readme = "README.md"
license = { text = "MIT" }

dynamic = ["dependencies"]

[tool.setuptools.packages.find]
include = ["modis", "modis.*"]
where = ["."]

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }