dataset_name: intersim_2_delta
model_name: intersim
latent_size: 64
modalities:
  - name: dna_methyl
    input_size: 367
  - name: gene_expr
    input_size: 131
  - name: protein_exp
    input_size: 160
training_mode: supervised
num_classes: 5
batch_size: 32
num_epochs: 10
generators_lr: 1e-4
discriminator_lr: 1e-4
beta: 5e-4
beta1: 0.5
lambda_r: 10.0
device: auto